Creating an array

In [ ]:
import numpy as np

In [ ]:
list1 = [3.5,4,23,0]
arr1 = np.array(list1)

In [ ]:
list1

[3.5, 4, 23, 0]

In [ ]:
arr1

array([ 3.5,  4. , 23. ,  0. ])

In [ ]:
list2 = (5,67,4.5,22,1)
arr2 = np.array(list2)

In [ ]:
list2

(5, 67, 4.5, 22, 1)

In [ ]:
arr2

array([ 5. , 67. ,  4.5, 22. ,  1. ])

Size of massive

In [ ]:
arr1.ndim

1

In [ ]:
arr2.ndim

1

In [ ]:
data3=[[2,3,4,5], [34,43,2,22]]
arr3=np.array(data3)

In [ ]:
data3
arr3

array([[ 2,  3,  4,  5],
       [34, 43,  2, 22]])

In [ ]:
data4=[[[76,54,44], [43,88,56]], [[76,44,32], [44,66,77]]]
arr4=np.array(data4)

In [ ]:
data4
arr4

array([[[76, 54, 44],
        [43, 88, 56]],

       [[76, 44, 32],
        [44, 66, 77]]])

In [ ]:
arr4.ndim

3

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr.shape

(2, 4)