In [1]:
import numpy as np

In [4]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.save("Data", arr)

In [6]:
np.load('Data.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1=np.arange(10,20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.savez('arrays', a=arr, b=arr1)

In [21]:
arrays=np.load('arrays.npz')

In [22]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arrays['b']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])