In [2]:
import numpy as np

Ex: 1

Transposing

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A.ndim

2

Creating an array transpose and returning back

In [ ]:
B=np.random.randn(3,4)
B

array([[ 0.40408278, -1.61505587,  0.47450417,  0.87025489],
       [-1.17186732,  1.62213168,  0.16248191, -0.69047065],
       [-0.22544483, -1.44472888,  0.60380772, -0.21228782]])

In [ ]:
C=B.T
C

array([[ 0.40408278, -1.17186732, -0.22544483],
       [-1.61505587,  1.62213168, -1.44472888],
       [ 0.47450417,  0.16248191,  0.60380772],
       [ 0.87025489, -0.69047065, -0.21228782]])

In [ ]:
C.T

array([[ 0.40408278, -1.61505587,  0.47450417,  0.87025489],
       [-1.17186732,  1.62213168,  0.16248191, -0.69047065],
       [-0.22544483, -1.44472888,  0.60380772, -0.21228782]])

Verifying dimensions

In [ ]:
C.ndim

2

In [ ]:
C.shape

(4, 3)

Ex: 2

In [4]:
arr=np.random.randn(5,5)
arr

array([[-0.72971433, -0.51162419,  0.87768575, -1.46810147, -0.45197945],
       [ 1.83699615,  0.7222446 , -1.45794484, -0.01367656, -1.89637469],
       [-0.15212783,  0.82829632,  0.29427796,  0.54384622,  0.77845045],
       [-1.1521673 ,  1.66508894, -0.61651505, -0.23971859,  1.04613643],
       [ 0.28311133, -1.62933679, -0.64355669,  1.0457755 , -0.50856378]])

Ex: 3

In [5]:
arr=np.random.rand(2,3,4)
arr

array([[[0.13012886, 0.94818507, 0.82038234, 0.09664192],
        [0.93769134, 0.84886119, 0.68229362, 0.84427306],
        [0.18133072, 0.63993494, 0.2412182 , 0.05278102]],

       [[0.26327673, 0.85593307, 0.5210193 , 0.70988413],
        [0.17148339, 0.92130567, 0.43605939, 0.7523545 ],
        [0.88066386, 0.80551113, 0.5836095 , 0.31056202]]])

In [6]:
arr.ndim

3

In [7]:
arr.shape

(2, 3, 4)