In [2]:
import numpy as np

One Dimensional Indexing

In [3]:
arr1d=np.arange(5,26,5)
arr1d[1]

10

In [4]:
arr=np.arange(2,11,2)
arr[-1]

10

In [6]:
arr=np.arange(1,10,2)
arr[3]=10
arr

array([ 1,  3,  5, 10,  9])

Slicing

In [7]:
arr=np.arange(3,28,3)
arr[2:7]

array([ 9, 12, 15, 18, 21])

In [9]:
arr=np.arange(2,19,2)
arr[:5]

array([ 2,  4,  6,  8, 10])

In [3]:
arr = np.array([1, 4, 9, 16, 25, 36, 49, 64, 81])
arr[::2]

array([ 1,  9, 25, 49, 81])

2 Dimensional indexing

In [5]:
arr_2d = np.array([[3, 6, 9], [12, 15, 18], [21, 24, 27]])
arr_2d[1:,0:2]

array([[12, 15],
       [21, 24]])

In [6]:
arr_2d = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
arr_2d[0,:2]

array([2, 4])