In [1]:
import numpy as np

In [8]:
names=np.array(['Suxrob','Jamshid',"Sherzod", 'Allibek', 'Otabek', 'Murod', 'Ikrom'])

In [27]:
data=np.random.randn(7,4)

In [28]:
data

array([[-1.10299357, -0.50770305,  0.72884854, -0.40589057],
       [ 0.2871996 ,  1.05256985,  0.57268071, -0.93647607],
       [-0.78502417, -0.12251945, -0.65724058, -0.58755642],
       [-0.33558949, -0.08213657,  0.99220664,  1.15430799],
       [ 0.83736444,  1.13627997, -0.27681848,  2.12364961],
       [ 0.02833109,  0.75306236,  0.83627705, -1.83277192],
       [-0.27013201,  0.94417708, -0.44512009,  1.39148397]])

In [9]:
names=='Jamshid'

array([False,  True, False, False, False, False, False])

In [10]:
data[names=='Jamshid']

array([[ 0.419262  , -0.84923276, -2.41559776, -0.25813594]])

In [19]:
mask = (names=='Jamshid') | (names=='Suxrob')
mask

array([ True,  True, False, False, False, False, False])

In [20]:
data[mask]

array([[ 1.26616508, -0.64061936, -0.07752863,  0.54821249],
       [ 0.419262  , -0.84923276, -2.41559776, -0.25813594]])

In [29]:
data

array([[-1.10299357, -0.50770305,  0.72884854, -0.40589057],
       [ 0.2871996 ,  1.05256985,  0.57268071, -0.93647607],
       [-0.78502417, -0.12251945, -0.65724058, -0.58755642],
       [-0.33558949, -0.08213657,  0.99220664,  1.15430799],
       [ 0.83736444,  1.13627997, -0.27681848,  2.12364961],
       [ 0.02833109,  0.75306236,  0.83627705, -1.83277192],
       [-0.27013201,  0.94417708, -0.44512009,  1.39148397]])

In [30]:
data[data<0]

array([-1.10299357, -0.50770305, -0.40589057, -0.93647607, -0.78502417,
       -0.12251945, -0.65724058, -0.58755642, -0.33558949, -0.08213657,
       -0.27681848, -1.83277192, -0.27013201, -0.44512009])

In [31]:
data[data<0]=0

In [32]:
data

array([[0.        , 0.        , 0.72884854, 0.        ],
       [0.2871996 , 1.05256985, 0.57268071, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.99220664, 1.15430799],
       [0.83736444, 1.13627997, 0.        , 2.12364961],
       [0.02833109, 0.75306236, 0.83627705, 0.        ],
       [0.        , 0.94417708, 0.        , 1.39148397]])

1. Greater Than Threshold:

Given an array arr = np.array([10, 15, 20, 25, 30]), use boolean indexing to print elements greater than 20.

In [34]:
arr=np.arange(10,31,5)
arr[arr>20]

array([25, 30])

2. Even Numbers:

Create an array arr = np.array([2, 7, 12, 18, 23, 30]). Use boolean indexing to print only the even numbers.

In [37]:
arr = np.array([2, 7, 12, 18, 23, 30])
arr[arr%2==0]

array([ 2, 12, 18, 30])

3. Negative Values:

Given the array arr = np.array([-3, 5, -8, 10, -12, 15]), use boolean indexing to print only the negative values.

In [38]:
arr = np.array([-3, 5, -8, 10, -12, 15])
arr[arr<0]

array([ -3,  -8, -12])

4. Divisible by 3:

Create an array arr = np.array([9, 14, 21, 26, 33, 38]). Use boolean indexing to print elements divisible by 3.

In [39]:
arr = np.array([9, 14, 21, 26, 33, 38])
arr[arr%3==0]

array([ 9, 21, 33])

5. Between a Range:

Given the array arr = np.array([25, 30, 35, 40, 45, 50]), use boolean indexing to print elements between 30 and 45 (inclusive).

In [41]:
arr = np.array([25, 30, 35, 40, 45, 50])


In [42]:
arr[(arr>=30) & (arr<=45)]

array([30, 35, 40, 45])