In [1]:
import numpy as np

Unary Functions.
Ex 1

In [5]:
arr=np.random.rand(5)
arr

array([0.42533304, 0.73039952, 0.74093483, 0.58728287, 0.30965068])

In [6]:
np.sqrt(arr)
arr

array([0.42533304, 0.73039952, 0.74093483, 0.58728287, 0.30965068])

Ex 2

In [9]:
arr=np.random.rand(10)
arr1=np.exp(arr)
arr1

array([1.51846598, 1.83795403, 1.3272961 , 2.3179401 , 1.34855619,
       2.69817007, 1.57468057, 1.05901067, 2.24550688, 1.46931051])

Ex 3

In [11]:
arr=np.array([3.14,2.71,1.25])
arr1=np.modf(arr)
arr1

(array([0.14, 0.71, 0.25]), array([3., 2., 1.]))

Ex 4

In [12]:
arr=np.array([-5,0,7,2])
arr1=np.sign(arr)
arr1

array([-1,  0,  1,  1])

Ex 5

In [14]:
arr=np.array([1,2,np.nan,4])
arr1=np.isnan(arr)
arr1

array([False, False,  True, False])

Ex 6

In [15]:
arr=np.array([-3,-2,0,1,4,5])
arr1=np.fabs(arr)
arr1

array([3., 2., 0., 1., 4., 5.])

Ex 7

In [17]:
arr=np.array([1.2,3.4,5.6,7.8])
arr1=np.floor(arr)
arr1

array([1., 3., 5., 7.])

Ex 8

In [18]:
arr=np.array([1.2,3.4,5.6,7.8])
arr1=np.ceil(arr)
arr1

array([2., 4., 6., 8.])

Binary Functions
Ex 1

In [20]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.add(arr1,arr2)
arr3

array([5, 7, 9])

Ex 2

In [21]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.subtract(arr1,arr2)
arr3

array([-3, -3, -3])

Ex 3

In [22]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.multiply(arr1,arr2)
arr3

array([ 4, 10, 18])

Ex 4

In [25]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.power(arr1,arr2)
arr3

array([  1,  32, 729])

Ex 5

In [29]:
arr1=np.array([1,8,3])
arr2=np.array([4,5,6])
np.maximumß(arr1,arr2)


array([4, 8, 6])