1. Replace Zeros: Create an array with random values between -5 and 5. Replace all zeros with the value 100 using np.where.

In [1]:
import numpy as np

In [10]:
cond=([True,True,True,True,True,False,True,True,True,True])

In [12]:
y=100

In [7]:
x=np.arange(-5,5)
x

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [13]:
arr1=np.where(cond,x,y)
arr1

array([ -5,  -4,  -3,  -2,  -1, 100,   1,   2,   3,   4])

2. Greater Than Average: Create an array with random values. Find the average and use np.where to create a new array containing only values greater than the average.

In [18]:
x=np.random.randn(3,3)
x

array([[-0.56325792,  0.83501296, -0.9495565 ],
       [-2.22864201,  0.64313196, -0.62038743],
       [ 1.35827735,  0.73328578,  0.69143854]])

In [19]:
arr=np.mean(x)
arr

-0.011188586106935985

In [22]:
arr2=np.where(x>arr,x,0)
arr2

array([[0.        , 0.83501296, 0.        ],
       [0.        , 0.64313196, 0.        ],
       [1.35827735, 0.73328578, 0.69143854]])

3. Alternating Values: Create two arrays of equal length. Use np.where to create a new array that alternates between elements from the two arrays.

In [23]:
x=np.arange(6)
y=np.arange(6,12)

In [26]:
c=([True, False, True, False, True, False])

In [27]:
a=np.where(c,x,y)
a

array([ 0,  7,  2,  9,  4, 11])