1. Create a 3x4 array filled with random integers between 1 and 10. Calculate the mean of all elements, the mean of each row, and the mean of each column.

In [1]:
import numpy as np

In [5]:
arr=np.random.randint(1,10,10).reshape(2,5)
arr

array([[2, 7, 3, 4, 4],
       [1, 3, 8, 8, 4]])

In [6]:
mean=np.mean(arr)
mean

4.4

In [8]:
mean_row=np.mean(arr,axis=1)
mean_row

array([4. , 4.8])

In [9]:
mean_column=np.mean(arr,axis=0)
mean_column

array([1.5, 5. , 5.5, 6. , 4. ])

2. Generate a 5x5 array with values increasing linearly from 1 to 25. Calculate the cumulative sum along each row and each column.

In [11]:
arr=np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
cumsum=np.cumsum(arr)
cumsum

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300])

In [13]:
cumsum_1=np.cumsum(arr, axis=1)
cumsum_1

array([[  0,   1,   3,   6,  10],
       [  5,  11,  18,  26,  35],
       [ 10,  21,  33,  46,  60],
       [ 15,  31,  48,  66,  85],
       [ 20,  41,  63,  86, 110]])

In [14]:
cumsum_0=np.cumsum(arr,axis=0)
cumsum_0

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13],
       [15, 18, 21, 24, 27],
       [30, 34, 38, 42, 46],
       [50, 55, 60, 65, 70]])