Exercises for np.unique:

Create an array with various repeated elements. Find the unique elements and their counts.


In [10]:
import numpy as np

In [11]:
arr=np.array([3,33,33,44,44,234,23,4,66,4,234])

In [17]:
uq_elem, count=np.unique(arr, return_counts=True)
print(uq_elem)
count

[  3   4  23  33  44  66 234]


array([1, 2, 1, 2, 2, 1, 2])

Exercises for np.setdiff1d:

Create two arrays representing grocery lists. Find the items that are only in the first list.
Generate two arrays of random numbers. Identify the numbers that exist in the first array but not in the second.

In [22]:
arr1=np.array(['cookies','donuts','sprite','chips','milk'])
arr2=np.array(['lamb','stake','milk','water','donuts','chips'])
print(arr1,arr2)

['cookies' 'donuts' 'sprite' 'chips' 'milk'] ['lamb' 'stake' 'milk' 'water' 'donuts' 'chips']


In [23]:
diff=np.setdiff1d(arr1,arr2)
diff

array(['cookies', 'sprite'], dtype='<U7')

In [26]:
arr1=np.random.randint(10,30,10)
arr1

array([20, 16, 11, 13, 23, 13, 12, 16, 29, 28])

In [29]:
arr2=np.random.randint(10,30,10)
arr2

array([13, 12, 23, 15, 15, 10, 29, 23, 17, 25])

In [30]:
diff=np.setdiff1d(arr1,arr2)
diff

array([11, 16, 20, 28])

Exercises for np.in1d:

Create an array of student grades and a separate array of passing grades. Check which students passed.
Generate a list of email addresses and a list of subscribed users. Verify which emails belong to subscribers.

In [31]:
grades=np.array([3,4,2,5,1,3,3,4,5,3,2,4,5])
passing_grades=np.array([4,5])

In [32]:
results=np.in1d(grades,passing_grades)
results

array([False,  True, False,  True, False, False, False,  True,  True,
       False, False,  True,  True])

In [33]:
emails=np.array(['sher.san@bk.com','suxa.ochilov@02.ru','jama.jamti@2000.com'])
subscribers=np.array(['sher.san@bk.com', 'axa.ochilov@97.uz'])

In [34]:
results=np.in1d(emails,subscribers)
results

array([ True, False, False])