# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [5]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [2]:
arr=np.array([2,32,234,5324,23,4])
arr

array([   2,   32,  234, 5324,   23,    4])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [6]:
arr=np.zeros(9)
size=arr.size
item=arr.itemsize
print(size)
print(item)

9
8


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
#Bu masalani yecha olmadim.

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [8]:
arr=np.zeros(12)
arr[5]=1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [9]:
arr=np.arange(20,60)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [14]:
arr=np.arange(15)
a=-np.sort(-arr)
print(f'Original array: {arr}')
print(f'Reversed array: {a}')

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Reversed array: [14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [16]:
arr=np.arange(12,21).reshape(3,3)
arr

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [19]:
arr=np.array([[3, 7, 0, 0, 9, 0]])
non_zero_array=np.nonzero(arr)
non_zero_array

(array([0, 0, 0]), array([0, 1, 4]))

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [21]:
arr=np.random.randn(8).reshape(2,2,2)
arr

array([[[-1.1103936 , -0.58728238],
        [ 1.13713156, -0.1438656 ]],

       [[ 0.479254  , -2.23921045],
        [ 2.36442101, -0.29906363]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [23]:
arr=np.random.randn(81).reshape(9,9)
max_value=np.max(arr)
min_value=np.min(arr)
print(max_value, min_value)

3.0739915240234654 -2.0884501229328074


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [29]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))
print(0.7==7*0.1)

nan
False
False
nan
True
False


#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [34]:
arr1=np.arange(18).reshape(6,3)
arr2=np.arange(18,30).reshape(3,4)
M=np.dot(arr1,arr2)
M

array([[  74,   77,   80,   83],
       [ 272,  284,  296,  308],
       [ 470,  491,  512,  533],
       [ 668,  698,  728,  758],
       [ 866,  905,  944,  983],
       [1064, 1112, 1160, 1208]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [8]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [6]:
a=np.array([1,2])
b=np.array([4,5])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [9]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-9-6caa14b62dca>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))
<ipython-input-9-6caa14b62dca>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [10]:
arr1=np.array([133,234,4,2,45,66,3])
arr2=np.array([87,451,133,4,54,45,3])
inter_sections=np.intersect1d(arr1,arr2)
inter_sections

array([  3,   4,  45, 133])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [15]:
arr=np.random.randn(5)
print(arr)
floor=np.floor(arr)
change_type=arr.astype(int)
truncate=np.trunc(arr)
print(floor)
print(change_type)
print(truncate)

[ 1.16158336 -0.57752408  1.94241475 -0.06314358  1.16101803]
[ 1. -1.  1. -1.  1.]
[1 0 1 0 1]
[ 1. -0.  1. -0.  1.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [17]:
arr=np.random.randint(0,3,9).reshape(3,3)
arr

array([[0, 1, 0],
       [1, 0, 0],
       [0, 2, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [18]:
arr=np.random.randn(10)
sorted=np.sort(arr)
print(f"Original array: {arr}")
print(f"Sorted array: {sorted}")

Original array: [ 0.70241016  0.47962388  0.65018277  1.3402139  -0.54969083  0.60770537
  0.74189588  0.02942022  0.53797251 -0.38846423]
Sorted array: [-0.54969083 -0.38846423  0.02942022  0.47962388  0.53797251  0.60770537
  0.65018277  0.70241016  0.74189588  1.3402139 ]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [24]:
A=np.random.randint(12,24)
B=np.random.randint(12,24)
C=np.allclose(A,B)
print(C)
C1=np.array_equal(A,B)
print(C1)

False
False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [26]:
arr=np.arange(18).reshape(6,3)
arr1=np.arange(15,27).reshape(3,4)
M=np.dot(arr,arr1)
M

array([[  65,   68,   71,   74],
       [ 236,  248,  260,  272],
       [ 407,  428,  449,  470],
       [ 578,  608,  638,  668],
       [ 749,  788,  827,  866],
       [ 920,  968, 1016, 1064]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [29]:
arr=np.random.randint(1,40,5)
print(arr)
Max=np.max(arr)
print(Max)
max_indice=np.argmax(arr)
arr[max_indice]=0
print(arr)

[ 2 31 25 24  6]
31
[ 2  0 25 24  6]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
#Uzr, buni bajara olmadim

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
#Uzr, buni bajara olmadim

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [31]:
arr=np.random.randint(3,45,5)
F=np.floor(arr)
A=arr.astype(int)
T=np.trunc(arr)
print(arr)
print(F)
print(A)
print(T)

[ 3  4  7 26  3]
[ 3.  4.  7. 26.  3.]
[ 3  4  7 26  3]
[ 3.  4.  7. 26.  3.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [32]:
arr=np.random.randint(1,10,5)
sum=np.add.reduce(arr)
sum

38

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
#Uzr, bu masalani yecholmadim

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [34]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14] )
b=np.stride_tricks.as_strided(a)
b

NameError: ignored

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`